name: Parallel CI/CD

on:
  push:
    branches:
      - main


jobs:

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Frontend Build
      run: |
        echo "Frontend build running"
        echo "Frontend deployed"


  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Backend Build
      run: |
        echo "Backend build running"
        echo "Backend deployed"


  database:
    name: Database
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Database Update
      run: |
        echo "Database migration running"
        echo "Database updated"