name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH To EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "SSH connection established" >>shahid.txt
            whoami
            hostname